<a href="https://colab.research.google.com/github/morenakukurin/Repo_AIbio/blob/4.-vela/5_velj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#data preprocessing tools

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [4]:
dataset = pd.read_csv('https://raw.githubusercontent.com/bio-chem-info/python_course/refs/heads/main/preprocess_data.csv')


In [8]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
a = dataset.tail(2).T #ispisi zadnja dva retka i transponiraj

In [6]:
a

8        9
Country    Germany   France
Age           50.0     37.0
Salary     83000.0  67000.0
Purchased       No      Yes

In [7]:
dataset.head(2)

Country   Age   Salary Purchased
0  France  44.0  72000.0        No
1   Spain  27.0  48000.0       Yes

In [13]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [10]:
X = dataset.iloc[:,:-1] #ne ukljuci zadnju kolonu
Y = dataset.iloc[:,-1] #ukljuci samo zadnju kolonu, to je vektor koji zelimo predvidjeti

In [11]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [12]:
Y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [16]:
X.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [21]:
X.isna().sum() #koliko je NaN vrijednosti po varijabli

Country    0
Age        1
Salary     1
dtype: int64

#Taking care of missing data

In [22]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [23]:
#nije u memoriji
X.fillna(0)

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      0.0
5   France  35.0  58000.0
6    Spain   0.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [24]:
#trajno zamijeniti u radnoj memoriji

X.fillna(0,inplace=True)

In [25]:
#stvori novi objekt, promjenjen na neki nacin
X1.fillna(1,inplace=True) #NE RADI JER TAJ OBJEKT VEC IMA POPUNJENE NaN

NameError: name 'X1' is not defined

In [26]:
X = dataset.iloc[:,:-1] #ne ukljuci zadnju kolonu
Y = dataset.iloc[:,-1] #ukljuci samo zadnju kolonu, to je vektor koji zelimo predvidjeti


In [29]:
X = X.fillna(-99)
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0    -99.0
5   France  35.0  58000.0
6    Spain -99.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [30]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,
                        strategy='median')

In [33]:
X = dataset.iloc[:,:-1] #ne ukljuci zadnju kolonu
Y = dataset.iloc[:,-1] #ukljuci samo zadnju kolonu, to je vektor koji zelimo predvidjeti
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [31]:
imputer

SimpleImputer(strategy='median')

In [39]:
#imputer.fit() #nauci, primjeti obrazac
imputer.fit(X[['Age','Salary']])
imputer.statistics_ #

array([3.8e+01, 6.1e+04])

In [34]:
X[['Age','Salary']].median()

Age          38.0
Salary    61000.0
dtype: float64

In [40]:
#fit,transform predict

In [42]:
X_imputed = imputer.transform(X[['Age','Salary']])
X_imputed

array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01, 6.1e+04],
       [3.5e+01, 5.8e+04],
       [3.8e+01, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

In [44]:
X_imp = pd.DataFrame(X_imputed,
                     columns = ['Age','Salary'],
                     index=X.index)
X_imp

Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0  61000.0
5  35.0  58000.0
6  38.0  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

In [45]:
#.fit nam daje obrazac po kojem se ponasaju podaci, jedn pravca npr.
#.transform je primjeni taj obrazac

#moj imputer za vjezbu

In [46]:
#-666 je prazno polje
vjezba = np.array([[2,3,-666],[3,2,1]])

In [47]:
vjezba

array([[   2,    3, -666],
       [   3,    2,    1]])

In [56]:
vjezba_df = pd.DataFrame(vjezba,
                         columns = ['Age','Salary','Broj'])

In [57]:
vjezba_df

Age  Salary  Broj
0    2       3  -666
1    3       2     1

In [70]:
imputer_vjezba = SimpleImputer(missing_values = -666,
                        strategy='mean')

In [71]:
imputer_vjezba.fit(vjezba_df[['Age','Salary','Broj']])


SimpleImputer(missing_values=-666)

In [72]:
vjezba_imputed = imputer_vjezba.transform(vjezba_df[['Age','Salary','Broj']])
vjezba_imputed

array([[2., 3., 1.],
       [3., 2., 1.]])

#encoding the independent variable

In [75]:
#uzme stupac, gleda koliko je jedinstvenih vrijednosti i onda ih pretvara u stupce s 0 i 1
X_encoded = pd.get_dummies(X, columns=['Country'])
X_encoded

Age   Salary  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0            True            False          False
1  27.0  48000.0           False            False           True
2  30.0  54000.0           False             True          False
3  38.0  61000.0           False            False           True
4  40.0      NaN           False             True          False
5  35.0  58000.0            True            False          False
6   NaN  52000.0           False            False           True
7  48.0  79000.0            True            False          False
8  50.0  83000.0           False             True          False
9  37.0  67000.0            True            False          False

In [76]:
X_encoded = pd.get_dummies(X, columns=['Country'], drop_first=True)
X_encoded

Age   Salary  Country_Germany  Country_Spain
0  44.0  72000.0            False          False
1  27.0  48000.0            False           True
2  30.0  54000.0             True          False
3  38.0  61000.0            False           True
4  40.0      NaN             True          False
5  35.0  58000.0            False          False
6   NaN  52000.0            False           True
7  48.0  79000.0            False          False
8  50.0  83000.0             True          False
9  37.0  67000.0            False          False

In [78]:
X_encoded = X_encoded.replace({True:1,False:0})
X_encoded

/tmp/ipython-input-527832612.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_encoded = X_encoded.replace({True:1,False:0})


Age   Salary  Country_Germany  Country_Spain
0  44.0  72000.0                0              0
1  27.0  48000.0                0              1
2  30.0  54000.0                1              0
3  38.0  61000.0                0              1
4  40.0      NaN                1              0
5  35.0  58000.0                0              0
6   NaN  52000.0                0              1
7  48.0  79000.0                0              0
8  50.0  83000.0                1              0
9  37.0  67000.0                0              0

In [81]:
Y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [107]:
Y_encoded = Y.replace({'Yes':1,'No':0})

/tmp/ipython-input-3469043380.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Y_encoded = Y.replace({'Yes':1,'No':0})


In [108]:
Y_encoded

0    0
1    1
2    0
3    0
4    1
5    1
6    0
7    1
8    0
9    1
Name: Purchased, dtype: int64

In [96]:
Y_encoded_2 = pd.get_dummies(Y)

In [97]:
Y_encoded_2

No    Yes
0   True  False
1  False   True
2   True  False
3   True  False
4  False   True
5  False   True
6   True  False
7  False   True
8   True  False
9  False   True

In [100]:
Y_encoded_2 = Y_encoded_2.replace({True:1,False:0},inplace=True)

In [103]:
Y_encoded_2

In [102]:
Y1 = Y_encoded_2.drop[]

TypeError: 'NoneType' object is not subscriptable

In [105]:
Y_encoded_2

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_encoded,
                                                    Y_encoded,
                                                    test_size = 0.25,
                                                    random_state=1)

In [113]:
X_train.describe

<bound method NDFrame.describe of     Age   Salary  Country_Germany  Country_Spain
4  40.0      NaN                1              0
0  44.0  72000.0                0              0
3  38.0  61000.0                0              1
1  27.0  48000.0                0              1
7  48.0  79000.0                0              0
8  50.0  83000.0                1              0
5  35.0  58000.0                0              0>

In [112]:
y_train

4    1
0    0
3    0
1    1
7    1
8    0
5    1
Name: Purchased, dtype: int64

In [114]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler
sc
#mora nauciti aritm sred i stand devijaciju za z scaling


In [116]:
sc.mean_ #jer jos nije naucio mean, moramo ga fitat

AttributeError: 'MinMaxScaler' object has no attribute 'mean_'

In [117]:
sc.fit(X_train)

MinMaxScaler()

In [120]:
sc.scale_
devijacija = X_train.std() #stupca
devijacija

Age                    7.931252
Salary             13437.509690
Country_Germany        0.487950
Country_Spain          0.487950
dtype: float64

In [119]:
sc.scale_

array([4.34782609e-02, 2.85714286e-05, 1.00000000e+00, 1.00000000e+00])

In [115]:
X_train_sc = pd.DataFrame(X_train_sc, columns=X_train.columns,index = X_train.index)
X_train_sc

Age    Salary  Country_Germany  Country_Spain
4  0.565217       NaN              1.0            0.0
0  0.739130  0.685714              0.0            0.0
3  0.478261  0.371429              0.0            1.0
1  0.000000  0.000000              0.0            1.0
7  0.913043  0.885714              0.0            0.0
8  1.000000  1.000000              1.0            0.0
5  0.347826  0.285714              0.0            0.0

In [121]:
X_train.var()

Age                6.290476e+01
Salary             1.805667e+08
Country_Germany    2.380952e-01
Country_Spain      2.380952e-01
dtype: float64

In [129]:
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)


In [130]:
X_train_sc = pd.DataFrame(X_train_sc, columns=X_train.columns, index = X_train.index)

In [131]:
X_train_sc

Age    Salary  Country_Germany  Country_Spain
4  0.565217       NaN              1.0            0.0
0  0.739130  0.685714              0.0            0.0
3  0.478261  0.371429              0.0            1.0
1  0.000000  0.000000              0.0            1.0
7  0.913043  0.885714              0.0            0.0
8  1.000000  1.000000              1.0            0.0
5  0.347826  0.285714              0.0            0.0

In [132]:
X_train_sc.describe()

Age    Salary  Country_Germany  Country_Spain
count  7.000000  6.000000         7.000000       7.000000
mean   0.577640  0.538095         0.285714       0.285714
std    0.344837  0.383929         0.487950       0.487950
min    0.000000  0.000000         0.000000       0.000000
25%    0.413043  0.307143         0.000000       0.000000
50%    0.565217  0.528571         0.000000       0.000000
75%    0.826087  0.835714         0.500000       0.500000
max    1.000000  1.000000         1.000000       1.000000

In [139]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler
sc

sklearn.preprocessing._data.MinMaxScaler

In [142]:
X_train, X_test, y_train, y_test = train_test_split(X_encoded,
                                                    Y_encoded,
                                                    test_size = 0.25,
                                                    random_state=1)

In [145]:
X_train

Age   Salary  Country_Germany  Country_Spain
4  40.0      NaN                1              0
0  44.0  72000.0                0              0
3  38.0  61000.0                0              1
1  27.0  48000.0                0              1
7  48.0  79000.0                0              0
8  50.0  83000.0                1              0
5  35.0  58000.0                0              0

In [146]:
X_test

Age   Salary  Country_Germany  Country_Spain
2  30.0  54000.0                1              0
9  37.0  67000.0                0              0
6   NaN  52000.0                0              1

In [143]:
sc.fit(X_train)

TypeError: MinMaxScaler.fit() missing 1 required positional argument: 'X'