<a href="https://colab.research.google.com/github/morenakukurin/Repo_AIbio/blob/3.velj/predavanje1_Lana_%C5%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# predavanje 1


In [24]:
12

12

In [25]:
type(12)


int

In [26]:
type(12.5)

float

In [27]:
type('lana')

str

In [28]:
'apple'

'apple'

In [29]:
"apple"

'apple'

In [30]:
True

True

In [31]:
False

False

In [32]:
3 < 5

True

In [33]:
7 < 2

False

In [37]:
#dictionaries{} #svakoj varijabli dodajemo jos jednu varijablu
#list[] #nju mozemo mjenjat, povecat, smanjit, promjenit naziv
#tuple() #readonly, kada zelimo paziti da nam se ti podaci ne mjenjaju u kodu


SyntaxError: invalid syntax (ipython-input-2564070299.py, line 1)

In [36]:
[1,2,3]
type([1,2,3])

list

In [39]:
plants = {'apple':'a fruit', 'banana': 'a herb'}

In [40]:
type(plants)

dict

In [41]:
plants

{'apple': 'a fruit', 'banana': 'a herb'}

In [42]:
plants['banana']

'a herb'

In [45]:
import pandas as pd

In [46]:
pd.DataFrame(plants,[0,1])

apple  banana
0  a fruit  a herb
1  a fruit  a herb

In [47]:
squares = [1, 4, 9, 16, 25]

In [48]:
type(squares)

list

In [49]:
squares

[1, 4, 9, 16, 25]

In [50]:
squares[4] #u uglatu zagradu se upise index u listi

25

In [51]:
squares[-2]

16

In [52]:
squares[:] #od kud do kud zelimo da se nasa lista printa

[1, 4, 9, 16, 25]

In [53]:
squares[1:]

[4, 9, 16, 25]

In [54]:
squares[1:3] #ne ispise taj 3. (odnosno 4.), taj element nije ukljucen

[4, 9]

In [55]:
sq2 = squares + [36, 49, 64,81,100]


In [56]:
sq2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [98]:
x = ['jedan','cetiri','devet','sesnaest','dvadeset pet']
rijecnik = {}
i = 0
for rijec in x:
  rijecnik[rijec] = squares[i]
  i = i +1

print(rijecnik)

{'jedan': 1, 'cetiri': 4, 'devet': 9, 'sesnaest': 16, 'dvadeset pet': 25}


In [60]:
len(sq2[:5])

5

In [61]:
letters = ['a','b','c','d','e','f','g']
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [62]:
letters[1:2] = [1,2,3,4,5] # za ubacit tu listu izmedu indeksa 1 i 2

In [63]:
letters

['a', 1, 2, 3, 4, 5, 'c', 'd', 'e', 'f', 'g']

In [64]:
len(letters)

11

In [65]:
abs(1)

1

In [66]:
abs(-10)

10

In [71]:
import operator

In [72]:
operator.add(1,3)

4

In [79]:
print(1)

1


In [83]:
print('this'+'is' + ' ' + 'a'+'full'+'sentence.')

thisis afullsentence.


In [84]:
print('this','is','a')

this is a


In [86]:
print('michael','is','helping')

michael is helping


In [87]:
print(sq2[1:5])

[4, 9, 16, 25]


# funkcije

In [99]:
def our_function(x):
  '''This function multiplies its argument by 2.'''
  y = x*2
  return y

In [100]:
our_function(8)

16

In [101]:
type(our_function)

function

In [102]:
import math

In [103]:
def ph(c):
  '''Ova funkcija racuna pH otopine. koristi koncentraciju H+ iona u mol/L.
  it returns pH.'''
  ph_value = -math.log10(c)
  return ph_value

In [104]:
ph(0.001)

3.0

In [105]:
def ph1(c):
  return -math.log(c, 10)

In [106]:
ph1(0.001)

2.9999999999999996

In [107]:
def task(x,y):
  '''definicja'''
  print('This is the log10 of x', math.log10(x))
  print('This is the log10 of y', math.log10(y))
  new_number = math.log10(x) + math.log(y)
  print(f'\nThe result is below:\n{new_number}')


In [108]:
task(1000, 2.73)

This is the log10 of x 3.0
This is the log10 of y 0.436162647040756

The result is below:
4.004301609196869


In [109]:
def konv_eur(euro):
  '''Konverzija eura u danske krune.'''
  dkk = euro*7.55
  print('DKK:\n')
  return dkk


In [110]:
konv_eur(10)

DKK:



75.5

In [111]:
def plus(a, b, c, d):
  suma = a+b+c+d
  return suma

In [112]:
plus(1,2,3,4)

10

= i ==

In [114]:
#= je za dodjeljivanje vrijednosti, a == je ispitivanje da li je zaista ta vrijednost jednaka

In [115]:
k = (1,2,3)

In [116]:
1==1

True

In [117]:
width = 20
height = 5*90
height, width

(450, 20)

In [118]:
width == 30

False

In [119]:
width ==20

True

In [120]:
width = 30 #predefinirali smo vrijednost width

In [121]:
width == 30

True

In [123]:
cp1 = 'Tomo'
cp2 = 'Maria'
cp1, cp2

('Tomo', 'Maria')

In [124]:
width == height

False

In [125]:
width = height #ponovno smo definirali width

In [126]:
width

450

In [127]:
cp1 == cp2

False

In [128]:
cp1 != cp2 #razlicito '!='

True

is i is not

In [129]:
5 is 4

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-171648558.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 4


False

In [130]:
5 is not 4

<>:1: SyntaxWarning: "is not" with 'int' literal. Did you mean "!="?
<>:1: SyntaxWarning: "is not" with 'int' literal. Did you mean "!="?
/tmp/ipython-input-2868815852.py:1: SyntaxWarning: "is not" with 'int' literal. Did you mean "!="?
  5 is not 4


True

In [131]:
width is height

True

In [132]:
width is not height

False

liste

In [133]:
squares

[1, 4, 9, 16, 25]

In [134]:
squares.append(36)
squares

[1, 4, 9, 16, 25, 36]

In [135]:
squares_part2= squares + [36]

In [136]:
squares

[1, 4, 9, 16, 25, 36]

In [137]:
squares_part2

[1, 4, 9, 16, 25, 36, 36]

In [139]:
new_list = []
new_list.append(49)
new_list

[49]

In [140]:
last_list = squares.copy()
last_list

[1, 4, 9, 16, 25, 36]

In [144]:
squares.append(10)
print('last list:',last_list)
print('squares:', squares)

last list: [1, 4, 9, 16, 25, 36]
squares: [1, 4, 9, 16, 25, 36, 10, 10, 10, 10]


In [145]:
print('patricipants in the course were', cp1, 'and', cp2)

patricipants in the course were Tomo and Maria


In [146]:
print(f'participants in the course were {cp1} and {cp2}.')

participants in the course were Tomo and Maria.


In [147]:
print('participants in the course were %s and %s.'
%(cp1,cp2)) #deiniranje s %s

participants in the course were Tomo and Maria.


In [148]:
print('participants in the course were %p and %p.'
%(cp1,cp2))

ValueError: unsupported format character 'p' (0x70) at index 33

In [150]:
sample = 'u552'
conc = 0.002
print('In a sample %s we found %s mg/L of drugs'%(sample, conc))

In a sample u552 we found 0.002 mg/L of drugs


In [151]:
def bmi(w, h):
  bmi = w/(h**2)
  return bmi

In [153]:
bmi(70,1.83)

20.902385858042937

#formula razrjedenja


In [154]:
def diluter(c1, v1=1, v2=2):
  "calculating dilution. return concentration."
  c2 = (c1*v1)/v2
  return c2

In [156]:
diluter(0.5) #treba se definirati samo c1, jer je v1 i v2 su vec definirani u funkciji

0.25

In [157]:
help(diluter)

Help on function diluter in module __main__:

diluter(c1=0.5, v1=1, v2=2)
    calculating dilution. return concentration.



In [158]:
diluter(2,1,3) #uzima u obzir i ako redefiniramo vec definirane argumente

0.6666666666666666

In [159]:
def factor_corrections(c, f=1):
  conc = c*f
  return conc

In [160]:
factor_corrections(0.0002, 2)

0.0004

In [161]:
def do_som_else(a=1,b=2,c=3):
  return(a,b,c)

In [163]:
do_som_else()

(1, 2, 3)

In [164]:
do_som_else(10,10)

(10, 10, 3)

In [166]:
def suma(a,b):
  return a+b

def adding_3rd(a,b,c):
  return suma(a,b)+c

In [169]:
adding_3rd(1,2,3)

6

#for loop

In [170]:
my_friends = ['Michael','Tomo','Maria','Peter']

In [172]:
for person in my_friends:
  print(person)

Michael
Tomo
Maria
Peter


In [173]:
i = 0
for person in my_friends:
  i = i+1
  print(i)

1
2
3
4


In [174]:
i = 0
for person in my_friends:
  i = i+1
print(i)

4


In [175]:
def bmi(w, h):
  bmi = w/(h**2)
  return bmi


In [177]:
weights = [80,90,55,70]
heights = [1.8,2.0,1.6,1.55]

for x,friend in enumerate(my_friends): #x je za dobiti index iz liste
  bmi_person = bmi(weights[x], heights[x])

  print(f'{friend} has the bmi of {bmi_person}')

Michael has the bmi of 24.691358024691358
Tomo has the bmi of 22.5
Maria has the bmi of 21.484374999999996
Peter has the bmi of 29.1363163371488


In [178]:
print(f'{friend} has the bmi of {bmi_person}') #zapamtio je zadnji koji je izracunao

Peter has the bmi of 29.1363163371488


In [179]:
squares = [1,4,9,16,25]

In [180]:
for x in squares:
  print('Element is %s'%x)

Element is 1
Element is 4
Element is 9
Element is 16
Element is 25


In [181]:
for number in squares:
  print(number)

1
4
9
16
25


In [182]:
course_participants = [cp1, cp2]

In [183]:
course_participants

['Tomo', 'Maria']

In [184]:
for name in course_participants:
  print(name)

Tomo
Maria


In [185]:
for position in range(len(course_participants)):
  print(position)

0
1


In [186]:
for number, element in enumerate(squares):
  print(number, element)

0 1
1 4
2 9
3 16
4 25


In [188]:
for number in squares:
  sq_root = math.sqrt(number)
  print(f'sgrt({number}):',sq_root)

sgrt(1): 1.0
sgrt(4): 2.0
sgrt(9): 3.0
sgrt(16): 4.0
sgrt(25): 5.0


#if else

In [189]:
1 <= 2

True

In [190]:
if 1 == 1:
  print('YES')

YES


In [191]:
if 1<1:
  print('YES')
else:
  print('NO')

NO


In [192]:
if 1<1:
  print("YES") #ne ispise nista, jer mu nismo dali else

In [193]:
cp1 = 'Mila'
cp2 = 'Marko'

In [196]:
if cp1 == cp2:
  print('DA')
else:
  print('NE')

NE


In [197]:
def check_gender_by_name(name):
  if name[-1] == 'a': #za definirati zadje slovo imena
    gender = 'female'
  elif name[-1]=='o':
    gender = 'male'
  else:
    gender = 'unknown'
  return gender

In [199]:
check_gender_by_name('Morena')

'female'

In [200]:
def ph(c):
  return -math.log10(c)

In [203]:
ph(0.003)

2.5228787452803374

In [204]:
def ph_evaluator(c=0.001):
  '''pH decision maker.'''
  ph_value = ph(c)
  if ph_value < 7:
    decision = 'acid'
  else:
    decision = 'luznato'
  return decision

In [205]:
ph_evaluator(0.002)

'acid'

In [206]:
def ph_evaluator(c=0.001):
  if ph(c) < 7:
    return "kiselo"
  else:
    return 'luznato'
conc_list = [0.001, 0.01, 1, 10]

for solution in conc_list:
  print(ph_evaluator(solution))

kiselo
kiselo
kiselo
kiselo


In [209]:
def test_if_else(a,b):
  '''a,b su argumenti. return da li je vece ili nije.'''
  if a > b:
    print(a, '>', b)
  else:
    print (a, 'nije vece od', b)

In [210]:
test_if_else

<function __main__.test_if_else(a, b)>

In [211]:
test_if_else(4,5)

4 nije vece od 5


In [212]:
def rectangle_area(a,b):
  '''dokumentacija'''
  A = a*b
  if a == b:
    print('kvadrat')
  else:
    print('pravokutnik')
    return A

In [213]:
rectangle_area(2,3)

pravokutnik


6

In [214]:
rectangle_area


<function __main__.rectangle_area(a, b)>

In [215]:
for letter in [1,2,3]:
  print('broj:', letter)

broj: 1
broj: 2
broj: 3


dodjeljivanje objekata

In [216]:
x = 5
x=7

In [217]:
x

7

In [218]:
y = 2
x+y

9

In [219]:
povrsina = rectangle_area(5,4)

pravokutnik


In [220]:
povrsina

20

In [221]:
(-3)**4

81

In [222]:
a = [4,5,6]
n = [1,2,3]
x = a+n #lista

In [223]:
x

[4, 5, 6, 1, 2, 3]

In [224]:
x = [a,n] #matrica

In [225]:
x

[[4, 5, 6], [1, 2, 3]]

In [226]:
import numpy as np
nums1 = [1,2,3,4,5]
nums1

[1, 2, 3, 4, 5]

In [227]:
nums2 = np.array(nums1) #sprema brojeve liste nums1 u array oblik

In [228]:
nums2

array([1, 2, 3, 4, 5])

In [231]:
type(nums2)

numpy.ndarray

In [230]:
type(nums1)

list

In [232]:
max(nums1)

5

In [233]:
min(nums1)

1

In [234]:
np.min(nums1)

np.int64(1)

In [244]:
x1 = np.array([[1.3,0,2],[2.3,1.3,5]]) #mora biti LISTA

In [242]:
x1

array([[1.3, 0. , 2. ],
       [2.3, 1.3, 5. ]])

In [245]:
x2 = np.array([1,2,3])
x2.dtype

dtype('int64')

In [246]:
x1.dtype, type(x1)

(dtype('float64'), numpy.ndarray)

In [250]:
x2 = np.arange(20,50,2)
x2


array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [253]:
np.linspace(10,20,10, endpoint = True) #ukljucili smo i 20 u listu, rastavlja brojevni pravac na 10 jednakih djelova

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [254]:
nule=np.zeros((5,3)) #matrica s nulama, 5 redaka i 5 kolona

In [255]:
nule.shape

(5, 3)

In [256]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [258]:
x4 = np.random.random((3,10)) #mora biti random.random

In [259]:
x4

array([[0.68810708, 0.09914593, 0.09492265, 0.7462463 , 0.71862907,
        0.05747083, 0.83778046, 0.51787279, 0.48590632, 0.0777723 ],
       [0.69813672, 0.24315582, 0.05343623, 0.59744722, 0.60196772,
        0.43471717, 0.4930754 , 0.8102976 , 0.97612194, 0.05324168],
       [0.25134436, 0.36026767, 0.94733175, 0.59686151, 0.22948166,
        0.91007097, 0.72383181, 0.34580205, 0.93664935, 0.75256765]])

In [260]:
pd.DataFrame(x4) #pandas je dobar za raditi tablice

0         1         2         3         4         5         6  \
0  0.688107  0.099146  0.094923  0.746246  0.718629  0.057471  0.837780   
1  0.698137  0.243156  0.053436  0.597447  0.601968  0.434717  0.493075   
2  0.251344  0.360268  0.947332  0.596862  0.229482  0.910071  0.723832   

          7         8         9  
0  0.517873  0.485906  0.077772  
1  0.810298  0.976122  0.053242  
2  0.345802  0.936649  0.752568

In [261]:
x4.dtype

dtype('float64')

In [264]:
x4.shape

(3, 10)

In [265]:
x4.reshape(10,3)

array([[0.68810708, 0.09914593, 0.09492265],
       [0.7462463 , 0.71862907, 0.05747083],
       [0.83778046, 0.51787279, 0.48590632],
       [0.0777723 , 0.69813672, 0.24315582],
       [0.05343623, 0.59744722, 0.60196772],
       [0.43471717, 0.4930754 , 0.8102976 ],
       [0.97612194, 0.05324168, 0.25134436],
       [0.36026767, 0.94733175, 0.59686151],
       [0.22948166, 0.91007097, 0.72383181],
       [0.34580205, 0.93664935, 0.75256765]])

In [266]:
pd.DataFrame(x4)

0         1         2         3         4         5         6  \
0  0.688107  0.099146  0.094923  0.746246  0.718629  0.057471  0.837780   
1  0.698137  0.243156  0.053436  0.597447  0.601968  0.434717  0.493075   
2  0.251344  0.360268  0.947332  0.596862  0.229482  0.910071  0.723832   

          7         8         9  
0  0.517873  0.485906  0.077772  
1  0.810298  0.976122  0.053242  
2  0.345802  0.936649  0.752568

In [267]:
x4.T #transpose


array([[0.68810708, 0.69813672, 0.25134436],
       [0.09914593, 0.24315582, 0.36026767],
       [0.09492265, 0.05343623, 0.94733175],
       [0.7462463 , 0.59744722, 0.59686151],
       [0.71862907, 0.60196772, 0.22948166],
       [0.05747083, 0.43471717, 0.91007097],
       [0.83778046, 0.4930754 , 0.72383181],
       [0.51787279, 0.8102976 , 0.34580205],
       [0.48590632, 0.97612194, 0.93664935],
       [0.0777723 , 0.05324168, 0.75256765]])

In [268]:
np.arange(2,20).reshape(2,3,3).T

array([[[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]],

       [[ 4, 13],
        [ 7, 16],
        [10, 19]]])

In [274]:
I = np.eye(3) #jednice po dijagonali - jednicni matrix
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [270]:
A = np.arange(9).reshape(3,3)

In [272]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [275]:
I@A

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])